<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260109083429 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Aggiunta tabelle argomento, domanda e risposta';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE argomento (id_argomento INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome_argomento VARCHAR(110) NOT NULL, descrizione VARCHAR(255) NOT NULL, PRIMARY KEY (id_argomento))');
        $this->addSql('CREATE TABLE domanda (id_domanda INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, testo_domanda VARCHAR(255) NOT NULL, PRIMARY KEY (id_domanda))');
        $this->addSql('CREATE TABLE risposta (id_risposta INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, testo_risposta VARCHAR(255) NOT NULL, punteggio INT NOT NULL, PRIMARY KEY (id_risposta))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE argomento');
        $this->addSql('DROP TABLE domanda');
        $this->addSql('DROP TABLE risposta');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
