<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114103054 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Aggiunta Utente';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE utente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(30) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DE45B3E0E7927C74 ON utente (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON utente (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D9A4A9CCB8C786E ON argomento (nome_argomento)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE utente');
        $this->addSql('DROP INDEX UNIQ_4D9A4A9CCB8C786E');
    }
}
